# Dockerfile文件：自定义Docker镜像文件
# 声明需要用到的基础镜像
FROM java:8

# 声明基础信息
LABEL version="1.0"
LABEL description="This is a SpringBoot app !"

# 声明作者信息
MAINTAINER SkyLaker skylaker@ **.com

# 声明环境变量
ENV WORK_DIR=/app PORT=8020

# 声明工作目录 
WORKDIR $WORK_DIR

# 在镜像内部执行一些配置命令
RUN echo 'This is a restful app !' > readme.txt

# 将要运行的Java应用复制到镜像内
COPY spring-boot-test-0.0.1-SNAPSHOT.jar  $WORK_DIR/user.jar
COPY config/  $WORK_DIR/config/
COPY wait-for-it.sh $WORK_DIR/wait-for-it.sh
RUN chmod +777 $WORK_DIR/wait-for-it.sh


# 暴露镜像端口：这里为应用的访问端口
EXPOSE $PORT

# 添加数据卷：这里将日志文件目录添加为数据卷(注意是无法指定宿主机目录的)
VOLUME $WORK_DIR/log

# 设置容器启动命令：即启动Java应用
CMD $WORK_DIR/wait-for-it.sh  192.168.3.15:3306  -- java -jar $WORK_DIR/user.jar
